export const KECAMATAN_KUKAR = [
  "Anggana",
  "Kembang Janggut",
  "Kenohan",
  "Kota Bangun",
  "Kota Bangun Darat",
  "Loa Janan",
  "Loa Kulu",
  "Marang Kayu",
  "Muara Badak",
  "Muara Jawa",
  "Muara Kaman",
  "Muara Muntai",
  "Muara Wis",
  "Samboja",
  "Samboja Barat",
  "Sanga-Sanga",
  "Sebulu",
  "Tabang",
  "Tenggarong",
  "Tenggarong Seberang",
] as const;
